---
abstract: 'Moose Types related to Credit Cards'
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Moose: 0
  Test::Exception: 0
  Test::Fatal: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Types-CreditCard
no_index:
  file:
    - perlcritic.rc
provides:
  MooseX::Types::CreditCard:
    file: lib/MooseX/Types/CreditCard.pm
    version: 0.002002
requires:
  Business::CreditCard: 0
  Module::Runtime: 0
  MooseX::Types: 0
  MooseX::Types::Common::String: 0.001005
  MooseX::Types::DateTime: 0
  MooseX::Types::Moose: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/xenoterracide/MooseX-Types-CreditCard/issues
  homepage: http://search.cpan.org/dist/MooseX-Types-CreditCard/
  repository: git://github.com/xenoterracide/MooseX-Types-CreditCard.git
version: 0.002002
